/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary": "#006194",
        "on-primary": "#ffffff",
        "outline": "#6d7a77",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#001d31",
        "surface-variant": "#e0e3e5",
        "error": "#ba1a1a",
        "background": "#f7f9fb",
        "primary-fixed": "#dbeafe",
        "secondary-container": "#dae2fd",
        "on-secondary-fixed-variant": "#3f465c",
        "on-surface": "#191c1e",
        "on-error": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "surface-container-high": "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        "on-background": "#191c1e",
        "surface-tint": "#2563eb",
        "on-secondary-fixed": "#131b2e",
        "tertiary-fixed": "#cce5ff",
        "primary": "#2563eb",
        "tertiary-fixed-dim": "#93ccff",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface": "#f7f9fb",
        "on-surface-variant": "#3d4947",
        "on-primary-fixed-variant": "#1e40af",
        "secondary-fixed": "#dae2fd",
        "on-primary-container": "#eff6ff",
        "on-primary-fixed": "#172554",
        "surface-bright": "#f7f9fb",
        "secondary-fixed-dim": "#bec6e0",
        "on-tertiary-fixed-variant": "#004b73",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#fdfcff",
        "surface-container": "#eceef0",
        "primary-fixed-dim": "#bfdbfe",
        "secondary": "#565e74",
        "inverse-primary": "#93c5fd",
        "primary-container": "#1d4ed8",
        "error-container": "#ffdad6",
        "outline-variant": "#bcc9c6",
        "on-secondary-container": "#5c647a",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f3",
        "tertiary-container": "#007bb9",
        "surface-dim": "#d8dadc"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "2xl": "1.25rem",
        "3xl": "1.75rem",
        "squircle": "28px",
        "full": "9999px"
      },
      fontFamily: {
        "headline-sm": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-hero": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        inter: ["Inter", "sans-serif"],
        sans: ["Inter", "-apple-system", "BlinkMacSystemFont", "'Segoe UI'", "Roboto", "sans-serif"],
      },
      boxShadow: {
        'squircle': '0 4px 20px -2px rgba(15, 23, 42, 0.04), 0 2px 6px -1px rgba(15, 23, 42, 0.02)',
        'squircle-hover': '0 16px 36px -4px rgba(15, 23, 42, 0.08), 0 4px 14px -2px rgba(15, 23, 42, 0.03)',
        'squircle-elevated': '0 12px 32px -4px rgba(15, 23, 42, 0.06), 0 4px 12px -2px rgba(15, 23, 42, 0.03)'
      }
    },
  },
  plugins: [],
};
